const Store = require("electron-store");
const schema = {
  aiProvider:   { type:"string", enum:["claude","openai","gemini","groq","ollama","openrouter","deepseek"], default:"gemini" },
  aiModel:      { type:"string", default:"" },
  claudeApiKey:     { type:"string", default:"" },
  claudeModelCustom: { type:"string", default:"" },
  // Custom base URL for Claude (e.g. proxy or compatible API); defaults to official Anthropic endpoint
  claudeBaseUrl:    { type:"string", default:"https://api.anthropic.com" },

  openaiApiKey:     { type:"string", default:"" },
  openaiModelCustom: { type:"string", default:"" },
  // Custom base URL for OpenAI (e.g. Azure OpenAI or local proxy); defaults to official OpenAI endpoint
  openaiBaseUrl:    { type:"string", default:"https://api.openai.com/v1" },

  geminiApiKey:     { type:"string", default:"" },
  geminiModelCustom: { type:"string", default:"" },
  // Custom base URL for Gemini; defaults to official Google Generative Language API endpoint
  geminiBaseUrl:    { type:"string", default:"https://generativelanguage.googleapis.com/v1beta" },

  groqApiKey:     { type:'string', default:'' },
  groqModelCustom: { type:'string', default:'' },
  // Custom base URL for Groq (e.g. a Groq-compatible service); defaults to official Groq endpoint
  groqBaseUrl:    { type:"string", default:"https://api.groq.com/openai/v1" },

  openrouterApiKey: { type:'string', default:'' },
  openrouterModelCustom: { type:'string', default:'' },
  openrouterMaxTokens: { type:"number", default:2048 },
  // Custom base URL for OpenRouter; defaults to official OpenRouter endpoint
  openrouterBaseUrl: { type:"string", default:"https://openrouter.ai/api/v1" },

  deepseekApiKey: { type:"string", default:"" },
  deepseekModelCustom: { type:"string", default:"deepseek-chat" },
  deepseekBaseUrl: { type:"string", default:"https://api.deepseek.com" },

  ollamaUrl:    { type:"string", default:"http://localhost:11434" },
  ollamaModelCustom: { type:"string", default:"" },
  sttProvider:  { type:"string", enum:["assemblyai","whisper"], default:"assemblyai" },
  assemblyaiApiKey: { type:"string", default:"" },
  whisperApiKey:    { type:"string", default:"" },
  whisperBaseUrl:   { type:"string", default:"https://api.openai.com/v1" },
  whisperModel:     { type:"string", default:"whisper-1" },
  sttLanguage:  { type:"string", default:"en-US" },
  ttsProvider:  { type:"string", enum:["google","elevenlabs","openai"], default:"google" },
  openaiTtsApiKey: { type:"string", default:"" },
  openaiTtsBaseUrl: { type:"string", default:"https://api.openai.com/v1" },
  openaiTtsModel: { type:"string", default:"tts-1" },
  openaiTtsVoice: { type:"string", default:"nova" },
  ttsRate: { type:"number", default:1.5 },
  ttsVolume: { type:"number", default:1 },
  ttsEnabled:   { type:"boolean", default:true },
  elevenlabsApiKey:   { type:"string", default:"" },
  elevenlabsVoiceId:  { type:"string", default:"EXAVITQu4vr4xnSDxMaL" },
  pushToTalkShortcut: { type:"string", default:"Ctrl+Shift+Space" },
  markStepDoneShortcut: { type:"string", default:"Ctrl+Alt+1" },
  requestStepHelpShortcut: { type:"string", default:"Ctrl+Alt+2" },
  recheckCurrentStepShortcut: { type:"string", default:"Ctrl+Alt+3" },
  cancelActivePlanShortcut: { type:"string", default:"Ctrl+Alt+4" },
  previousStepShortcut: { type:"string", default:"Ctrl+Alt+5" },
  skipCurrentStepShortcut: { type:"string", default:"Ctrl+Alt+6" },
  regenerateCurrentStepShortcut: { type:"string", default:"Ctrl+Alt+7" },
  executionMode: { type:"string", enum:["hitl","auto"], default:"hitl" },
  trustLevel: { type:"string", enum:["paranoid","balanced","autopilot"], default:"balanced" },
  browserAgentEnabled: { type:"boolean", default:true },
  browserHeadless: { type:"boolean", default:false },
  webStudioEnabled: { type:"boolean", default:true },
  selfBuildEnabled: { type:"boolean", default:true },
  awareAssistanceEnabled: { type:"boolean", default:false },
  includeScreenshotByDefault: { type:"boolean", default:false },
  systemPromptOverride: { type:"string", default:"" },
  userMemoryFacts: { type:"array", default: [], items: { type:"string" } },
  planningModeEnabled: { type:"boolean", default:false },
  assistantMode: { type:"string", enum:["assistant","guide","fast","planning"], default:"assistant" },
  onboardingCompleted: { type:"boolean", default:false },
  pipelineAutoChain: { type:"boolean", default:true },
  panelWindowX: { type:"number", default:-1 },
  panelWindowY: { type:"number", default:-1 },
  sessionSnapshotV1: { type: ["object", "null"], default: null },
  chatSessionsV1: { type: ["object", "null"], default: null },
  workspacePath: { type: "string", default: "" },
  vscodePath: { type: "string", default: "" },
  finopsTotalBudgetTl: { type: "number", default: 0 },
  finopsHardBudgetEnabled: { type: "boolean", default: false },
  finopsUsdToTl: { type: "number", default: 34.5 },
  finopsDefaultPricePerMillionTl: { type: "number", default: 50 },
  finopsLastAlertDate: { type: "string", default: "" },
  finopsModelPriceOverrides: { type: "object", default: {} },
  finopsProviderPriceOverrides: { type: "object", default: {} },
  finopsDiscoveredModels: { type: "object", default: {} },
  finopsCostOptimizerEnabled: { type: "boolean", default: true },
  finopsCostOptimizerMode: { type: "string", enum: ["economy", "balanced", "performance"], default: "balanced" },
  finopsCoreModelTier: { type: "string", enum: ["economy", "standard", "premium", "local"], default: "economy" },
  finopsHandoffMaxChars: { type: "number", default: 4000 },
  finopsHandoffIncludeTranscript: { type: "boolean", default: false },
  finopsDailyBudgetTl: { type: "number", default: 0 },
  finopsOptimizerModels: { type: "object", default: {} },
  finopsAgentWallets: {
    type: "object",
    default: {
      gemini: { limitUsd: 0, topUpUsd: 0 },
      deepseek: { limitUsd: 0, topUpUsd: 0 },
      openai: { limitUsd: 0, topUpUsd: 0 },
      ollama: { limitUsd: 0, topUpUsd: 0 },
    },
  },
  finopsAgentWalletLastAlertDate: { type: "string", default: "" },
  agentMatrixVersion: { type: "number", default: 1 },
  chatBackupEnabled: { type: "boolean", default: false },
  chatBackupPath: { type: "string", default: "" },
  codeAgentNativeEnabled: { type: "boolean", default: false },
  codeAgentMaxIterations: { type: "number", default: 15 },
  finopsCodeContextMaxChars: { type: "number", default: 4000 },
  finopsDeltaHandoffEnabled: { type: "boolean", default: true },
  finopsClarifySkipEnabled: { type: "boolean", default: true },
  finopsClineOllamaForLow: { type: "boolean", default: false },
  finopsPanelContextMessages: { type: "number", default: 20 },
  finopsMemoryCompressThreshold: { type: "number", default: 40 },
  finopsMemoryCompressBatch: { type: "number", default: 20 },
  finopsPresetBackup: { type: "object", default: {} },
  gooseEnabled: { type: "boolean", default: true },
  gooseBinaryPath: { type: "string", default: "" },
  gooseDefaultMode: { type: "string", enum: ["economy", "balanced", "premium"], default: "balanced" },
  gooseDailyBudgetTl: { type: "number", default: 0 },
  gooseAutoMode: { type: "boolean", default: true },
  gooseBudgetAutoDowngrade: { type: "boolean", default: false },
  gooseBudgetWarnAt: { type: "number", default: 0.8 },
  gooseFinopsShareGlobalBudget: { type: "boolean", default: true },
  gooseShowModeHint: { type: "boolean", default: true },
  gamedevEnabled: { type: "boolean", default: true },
  gamedevActiveEngine: { type: "string", enum: ["unity", "unreal", "roblox", "blender"], default: "unity" },
  gamedevMcpEntryPath: { type: "string", default: "" },
  gamedevModeActive: { type: "boolean", default: false },
  gamedevDefaultTemplate: { type: "string", default: "auto" },
  gamedevPipelineAutoChain: { type: "boolean", default: true },
  gamedevDefaultMode: { type: "string", enum: ["economy", "balanced", "premium"], default: "economy" },
  gamedevPipelineId: { type: "string", default: "" },
  gamedevSetupComplete: { type: "boolean", default: false },
  gamedevMasterPrompt: { type: "string", default: "" },
  gamedevUseLlmPlan: { type: "boolean", default: false },
  gamedevBriefMaxChars: { type: "number", default: 8000 },
};
function createStore() { return new Store({ schema, clearInvalidConfig: true }); }
module.exports = { createStore, schema };
