const Store = require("electron-store");
const schema = {
  aiProvider:   { type:"string", enum:["claude","openai","gemini","groq","ollama","openrouter","deepseek"], default:"gemini" },
  aiModel:      { type:"string", default:"" },
  claudeApiKey:     { type:"string", default:"" },
  claudeModelCustom: { type:"string", default:"" },
  // Custom base URL for Claude (e.g. proxy or compatible API); defaults to official Anthropic endpoint
  claudeBaseUrl:    { type:"string", default:"https://api.anthropic.com" },

  openaiApiKey:     { type:"string", default:"" },
  openaiModelCustom: { type:"string", default:"" },
  // Custom base URL for OpenAI (e.g. Azure OpenAI or local proxy); defaults to official OpenAI endpoint
  openaiBaseUrl:    { type:"string", default:"https://api.openai.com/v1" },

  geminiApiKey:     { type:"string", default:"" },
  geminiModelCustom: { type:"string", default:"" },
  // Custom base URL for Gemini; defaults to official Google Generative Language API endpoint
  geminiBaseUrl:    { type:"string", default:"https://generativelanguage.googleapis.com/v1beta" },

  groqApiKey:     { type:'string', default:'' },
  groqModelCustom: { type:'string', default:'' },
  // Custom base URL for Groq (e.g. a Groq-compatible service); defaults to official Groq endpoint
  groqBaseUrl:    { type:"string", default:"https://api.groq.com/openai/v1" },

  openrouterApiKey: { type:'string', default:'' },
  openrouterModelCustom: { type:'string', default:'' },
  openrouterMaxTokens: { type:"number", default:2048 },
  // Custom base URL for OpenRouter; defaults to official OpenRouter endpoint
  openrouterBaseUrl: { type:"string", default:"https://openrouter.ai/api/v1" },

  deepseekApiKey: { type:"string", default:"" },
  deepseekModelCustom: { type:"string", default:"deepseek-chat" },
  deepseekBaseUrl: { type:"string", default:"https://api.deepseek.com" },

  ollamaUrl:    { type:"string", default:"http://localhost:11434" },
  ollamaModelCustom: { type:"string", default:"" },
  sttProvider:  { type:"string", enum:["assemblyai","whisper"], default:"assemblyai" },
  assemblyaiApiKey: { type:"string", default:"" },
  whisperApiKey:    { type:"string", default:"" },
  whisperBaseUrl:   { type:"string", default:"https://api.openai.com/v1" },
  whisperModel:     { type:"string", default:"whisper-1" },
  sttLanguage:  { type:"string", default:"en-US" },
  ttsProvider:  { type:"string", enum:["google","elevenlabs","openai"], default:"google" },
  openaiTtsApiKey: { type:"string", default:"" },
  openaiTtsBaseUrl: { type:"string", default:"https://api.openai.com/v1" },
  openaiTtsModel: { type:"string", default:"tts-1" },
  openaiTtsVoice: { type:"string", default:"nova" },
  ttsRate: { type:"number", default:1.5 },
  ttsVolume: { type:"number", default:1 },
  ttsEnabled:   { type:"boolean", default:true },
  elevenlabsApiKey:   { type:"string", default:"" },
  elevenlabsVoiceId:  { type:"string", default:"EXAVITQu4vr4xnSDxMaL" },
  pushToTalkShortcut: { type:"string", default:"Ctrl+Shift+Space" },
  markStepDoneShortcut: { type:"string", default:"Ctrl+Alt+1" },
  requestStepHelpShortcut: { type:"string", default:"Ctrl+Alt+2" },
  recheckCurrentStepShortcut: { type:"string", default:"Ctrl+Alt+3" },
  cancelActivePlanShortcut: { type:"string", default:"Ctrl+Alt+4" },
  previousStepShortcut: { type:"string", default:"Ctrl+Alt+5" },
  skipCurrentStepShortcut: { type:"string", default:"Ctrl+Alt+6" },
  regenerateCurrentStepShortcut: { type:"string", default:"Ctrl+Alt+7" },
  executionMode: { type:"string", enum:["hitl","auto"], default:"hitl" },
  trustLevel: { type:"string", enum:["paranoid","balanced","autopilot"], default:"balanced" },
  browserAgentEnabled: { type:"boolean", default:false },
  browserHeadless: { type:"boolean", default:false },
  webStudioEnabled: { type:"boolean", default:true },
  selfBuildEnabled: { type:"boolean", default:true },
  awareAssistanceEnabled: { type:"boolean", default:false },
  includeScreenshotByDefault: { type:"boolean", default:false },
  systemPromptOverride: { type:"string", default:"" },
  userMemoryFacts: { type:"array", default: [], items: { type:"string" } },
  ownerName: { type:"string", default:"Can" },
  activePersonaId: { type:"string", enum:["luna", "hiri"], default:"luna" },
  lunaMatureContentEnabled: { type:"boolean", default:false },
  assistantName: { type:"string", default:"Luna" },
  personalityPreset: { type:"string", default:"sauron-default" },
  introOnNewChat: { type:"boolean", default:true },
  customIntroMessage: { type:"string", default:"" },
  altGreetings: { type:"array", default: [], items: { type:"string" } },
  personalitySliders: {
    type: "object",
    default: {
      responseLength: 50,
      warmth: 70,
      flirtiness: 50,
      emoji: 30,
    },
  },
  personalityFeedbackNotes: { type:"array", default: [], items: { type:"string" } },
  lunaMaturePreferLocal: { type:"boolean", default:false },
  assistantAutoCodeRoute: { type:"boolean", default:true },
  codeAgentOpenStudioOnStart: { type:"boolean", default:true },
  activeScenarioId: { type:"string", default:"" },
  autoMemoryExtractionEnabled: { type:"boolean", default:false },
  lunaRelationshipEnabled: { type:"boolean", default:true },
  lunaRelationshipProfile: { type:"object", default: {} },
  lunaSelfTuningEnabled: { type:"boolean", default:true },
  lunaSelfProfile: { type:"object", default: {} },
  lunaSelfProfileLocks: { type:"object", default: {} },
  hiriSelfTuningEnabled: { type:"boolean", default:true },
  hiriSelfProfile: { type:"object", default: {} },
  hiriSelfProfileLocks: { type:"object", default: {} },
  panelAtFileContextEnabled: { type:"boolean", default:true },
  channelHintChipsEnabled: { type:"boolean", default:true },
  personaTtsVoiceEnabled: { type:"boolean", default:true },
  lunaTtsVoice: { type:"string", default:"nova" },
  hiriTtsVoice: { type:"string", default:"alloy" },
  codeSemanticSearchEnabled: { type:"boolean", default:true },
  codeStudioMonacoEnabled: { type:"boolean", default:true },
  personaAvatarEnabled: { type:"boolean", default:false },
  voiceChatLoopEnabled: { type:"boolean", default:false },
  exampleDialogues: { type:"array", default: [], items: { type:"string" } },
  enhancedOnboardingEnabled: { type:"boolean", default:true },
  webDeployHintEnabled: { type:"boolean", default:true },
  messageCostHintEnabled: { type:"boolean", default:true },
  gamedevQuickSetupDismissed: { type:"boolean", default:false },
  codeStudioV3Enabled: { type:"boolean", default:true },
  codeReadinessBadgeEnabled: { type:"boolean", default:true },
  codeAgentBatchEnabled: { type:"boolean", default:false },
  codeAgentCheckpointEnabled: { type:"boolean", default:true },
  codeAgentRepairLoopEnabled: { type:"boolean", default:false },
  codeAgentBackgroundEnabled: { type:"boolean", default:false },
  codeTabCompletionEnabled: { type:"boolean", default:false },
  codeLspEnabled: { type:"boolean", default:false },
  panelExtendedContextEnabled: { type:"boolean", default:true },
  gamedevBridgeMonitorEnabled: { type:"boolean", default:true },
  gamedevAutoEditorLaunch: { type:"boolean", default:true },
  gamedevAutoPluginInstall: { type:"boolean", default:true },
  gamedevAutoMcpStart: { type:"boolean", default:true },
  gamedevBridgeWaitMs: { type:"number", default:90000 },
  gamedevAutoScaffoldEnabled: { type:"boolean", default:false },
  gamedevPlayLoopEnabled: { type:"boolean", default:false },
  gamedevMcpDirectPhasesEnabled: { type:"boolean", default:false },
  gamedevUnityPackageEnabled: { type:"boolean", default:false },
  smartPluginProfileEnabled: { type:"boolean", default:true },
  pluginProfileMode: { type:"string", enum:["auto","manual"], default:"auto" },
  activePluginProfile: { type:"string", enum:["general","web","game","code","browser"], default:"general" },
  pluginProfileLastSwitchAt: { type:"string", default:"" },
  pluginProfileNotifyEnabled: { type:"boolean", default:true },
  assistantMode: { type:"string", enum:["assistant","guide","fast","planning"], default:"assistant" },
  onboardingCompleted: { type:"boolean", default:false },
  pipelineAutoChain: { type:"boolean", default:true },
  panelWindowX: { type:"number", default:-1 },
  panelWindowY: { type:"number", default:-1 },
  sessionSnapshotV1: { type: ["object", "null"], default: null },
  chatSessionsV1: { type: ["object", "null"], default: null },
  workspacePath: { type: "string", default: "" },
  vscodePath: { type: "string", default: "" },
  finopsTotalBudgetTl: { type: "number", default: 0 },
  finopsHardBudgetEnabled: { type: "boolean", default: false },
  finopsUsdToTl: { type: "number", default: 34.5 },
  finopsDefaultPricePerMillionTl: { type: "number", default: 50 },
  finopsLastAlertDate: { type: "string", default: "" },
  finopsModelPriceOverrides: { type: "object", default: {} },
  finopsProviderPriceOverrides: { type: "object", default: {} },
  finopsDiscoveredModels: { type: "object", default: {} },
  finopsCostOptimizerEnabled: { type: "boolean", default: true },
  finopsCostOptimizerMode: { type: "string", enum: ["economy", "balanced", "performance"], default: "balanced" },
  finopsCoreModelTier: { type: "string", enum: ["economy", "standard", "premium", "local"], default: "economy" },
  finopsHandoffMaxChars: { type: "number", default: 4000 },
  finopsHandoffIncludeTranscript: { type: "boolean", default: false },
  finopsDailyBudgetTl: { type: "number", default: 0 },
  finopsOptimizerModels: { type: "object", default: {} },
  finopsAgentWallets: {
    type: "object",
    default: {
      gemini: { limitUsd: 0, topUpUsd: 0 },
      deepseek: { limitUsd: 0, topUpUsd: 0 },
      openai: { limitUsd: 0, topUpUsd: 0 },
      ollama: { limitUsd: 0, topUpUsd: 0 },
    },
  },
  finopsAgentWalletLastAlertDate: { type: "string", default: "" },
  agentMatrixVersion: { type: "number", default: 1 },
  chatBackupEnabled: { type: "boolean", default: false },
  chatBackupPath: { type: "string", default: "" },
  codeAgentNativeEnabled: { type: "boolean", default: false },
  codeAgentMaxIterations: { type: "number", default: 15 },
  finopsCodeContextMaxChars: { type: "number", default: 4000 },
  finopsDeltaHandoffEnabled: { type: "boolean", default: true },
  finopsClarifySkipEnabled: { type: "boolean", default: true },
  finopsClineOllamaForLow: { type: "boolean", default: false },
  finopsPanelContextMessages: { type: "number", default: 20 },
  finopsMemoryCompressThreshold: { type: "number", default: 40 },
  finopsMemoryCompressBatch: { type: "number", default: 20 },
  finopsPresetBackup: { type: "object", default: {} },
  agentFailoverEnabled: { type: "boolean", default: true },
  agentFailoverNotifyEnabled: { type: "boolean", default: true },
  lastAgentFailover: { type: "object", default: {} },
  agentHealthSnapshot: { type: "object", default: {} },
  finopsTrackingOnly: { type: "boolean", default: false },
  finopsRestrictModels: { type: "boolean", default: false },
  finopsCoreModelOverlay: { type: "boolean", default: true },
  agentControlMode: { type: "string", enum: ["auto", "manual", "mixed"], default: "auto" },
  coreManualAgent: { type: "string", enum: ["gemini", "deepseek", "openai", "ollama"], default: "gemini" },
  clineManualAgent: { type: "string", enum: ["gemini", "deepseek", "openai", "ollama"], default: "deepseek" },
  gooseManualMode: { type: "string", enum: ["economy", "balanced", "premium"], default: "balanced" },
  coreRoutingMode: { type: "string", enum: ["auto", "manual"], default: "auto" },
  clineRoutingMode: { type: "string", enum: ["auto", "manual"], default: "auto" },
  gooseRoutingMode: { type: "string", enum: ["auto", "manual"], default: "auto" },
  tokenUltraEnabled: { type: "boolean", default: true },
  tokenUltraUseDeltaHandoff: { type: "boolean", default: true },
  tokenUltraUseSceneCache: { type: "boolean", default: true },
  tokenUltraUseRepoMap: { type: "boolean", default: true },
  tokenUltraSandboxToolOutput: { type: "boolean", default: true },
  tokenUltraMaxHandoffChars: { type: "number", default: 6000 },
  tokenUltraShowDashboard: { type: "boolean", default: true },
  tokenUltraDeltaOverlapMin: { type: "number", default: 0.5 },
  tokenUltraUseChangedFilesOnly: { type: "boolean", default: true },
  tokenUltraSmartAtFileTrim: { type: "boolean", default: true },
  tokenUltraPreferOllamaForExtract: { type: "boolean", default: true },
  tokenUltraAutoEconomyEnabled: { type: "boolean", default: false },
  tokenUltraPromptCacheEnabled: { type: "boolean", default: true },
  tokenUltraPanelContextSummary: { type: "boolean", default: true },
  tokenUltraAggressionLevel: { type: "string", enum: ["smart", "balanced", "max"], default: "smart" },
  incidentMemoryEnabled: { type: "boolean", default: true },
  incidentAutoApplyLowRisk: { type: "boolean", default: false },
  incidentAgentDiagnoseEnabled: { type: "boolean", default: true },
  gooseEnabled: { type: "boolean", default: true },
  gooseBinaryPath: { type: "string", default: "" },
  gooseDefaultMode: { type: "string", enum: ["economy", "balanced", "premium"], default: "balanced" },
  gooseDailyBudgetTl: { type: "number", default: 0 },
  gooseAutoMode: { type: "boolean", default: true },
  gooseBudgetAutoDowngrade: { type: "boolean", default: false },
  gooseBudgetWarnAt: { type: "number", default: 0.8 },
  gooseFinopsShareGlobalBudget: { type: "boolean", default: true },
  gooseShowModeHint: { type: "boolean", default: true },
  gooseMcpProfile: { type: "string", enum: ["minimal", "workspace", "full"], default: "workspace" },
  gooseRecipeId: { type: "string", default: "" },
  gamedevEnabled: { type: "boolean", default: true },
  gamedevActiveEngine: { type: "string", enum: ["unity", "unreal", "roblox", "blender"], default: "unity" },
  gamedevMcpEntryPath: { type: "string", default: "" },
  gamedevModeActive: { type: "boolean", default: false },
  gamedevDefaultTemplate: { type: "string", default: "custom" },
  gamedevPipelineAutoChain: { type: "boolean", default: true },
  gamedevDefaultMode: { type: "string", enum: ["economy", "balanced", "premium"], default: "economy" },
  gamedevPipelineId: { type: "string", default: "" },
  gamedevSetupComplete: { type: "boolean", default: false },
  gamedevMasterPrompt: { type: "string", default: "" },
  gamedevUseLlmPlan: { type: "boolean", default: false },
  gamedevBriefMaxChars: { type: "number", default: 8000 },
  gamedevToolProfile: { type: "string", enum: ["core", "full"], default: "core" },
};
function createStore() { return new Store({ schema, clearInvalidConfig: true }); }
module.exports = { createStore, schema };
